name: CI-CD Compiler

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run docker tests
        run: |
          docker compose build
          docker compose run --rm test


  deploy:
    runs-on: ubuntu-latest
    needs: test   # chỉ deploy nếu test pass

    steps:
      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd Complier_Online
            git fetch origin main
            git reset --hard origin/main
            sudo docker-compose down
            sudo docker-compose up -d --build production